/* eslint-disable no-unreachable */
/* eslint-disable global-require */

const Images = {
  star: require('./star.png'),
  background: require('./Background.png'),
  Common: {
    logo: {
      white: {
        sm: require('./logo/white/Logo-32.png'),
        md: require('./logo/white/Logo-64.png'),
        lg: require('./logo/white/Logo-128.png'),
      },
      sm: require('./logo/Logo-32x32.png'),
      md: require('./logo/Logo-64x64.png'),
      lg: require('./logo/Logo-128x128.png'),
    },
    Peter404: require('./peter404.png'),
    Window: require('./home/hero/window.png'),
    Goldaword: require('./goldaword.png'),
  },
  backgrounds: {
    advisorsSectionBg: require('./backgrounds/bgadvvisors.png'),
    creedSectionBg: require('./backgrounds/bgcreed.png'),
    defaultBg: require('./backgrounds/bg.png'),
    gradientBg: require('./backgrounds/gradientbg.jpg'),
    gradientBgRotated: require('./backgrounds/gradientbgrotated.jpg'),
    light: require('./backgrounds/bg-light.png'),
    downloadAppBg: require('./backgrounds/downloadapp_bg.png'),
    teamofuseBg: require('./backgrounds/teamofusebg.png'),
    teamBg: require('./backgrounds/teambg.png'),
    whitelistBg: require('./backgrounds/Whitelistbg.png'),
    nftBg2: require('./backgrounds/nft_bg2.png'),
    nftBg: require('./backgrounds/nftbg.png'),
    impaktIcongBg: require('./backgrounds/impaktIconBg.png'),
  },

  motionCapture: require('./motion-capture.webp'),
  burnAndEarn: require('./burn-to-earn-hero.webp'),
  computerVision: require('./computer-vision.png'),
  verification: require('./rich-icon.png'),
  wrong: require('./some-wrong.png'),

  impaktNFT: {
    nftCard: require('./home/nft-flat.png'),
  },
  advisor: {
    kevin: require('./advisor/kevin.png'),
    chris: require('./advisor/chris3.png'),
    tim: require('./advisor/tim.png'),
    kai: require('./advisor/kai.png'),
  },
  partners: {
    john: require('./partners/john.jpg'),
    jeremy: require('./partners/jeremy.png'),
  },
  team: {
    // cap: require('./team/cap.png'),
    dahaka: require('./team/dahaka.png'),
    demideus: require('./team/demideus.png'),
    duke: require('./team/duke.png'),
    valtec: require('./team/valtec.png'),
    ratSpeare: require('./team/ratSpeare.png'),
    berila: require('./team/berila.png'),
    catRoutines: require('./team/catRoutines.png'),
    JSolo: require('./team/JSolo.png'),
    requiem: require('./team/requiem.png'),
    // dukeOfDeadfall: require('./team/duke-of-deadfall.png'),
  },
  contactUs: {
    discordPeter: require('./discordPeter.png'),
    hiPeter: require('./hiPeter.png'),
  },
  impaktIcons: {
    MattFox: require('./home/Icons/Matt-Fox.png'),
    KelvinGastelum: require('./home/Icons/Kelvin-Gastelum.png'),
    ThirdIcon: require('./home/Icons/thirdIcon.png'),
    Icon1: require('./home/Icons/Icon1.png'),
    Icon2: require('./home/Icons/Icon2.png'),
    Icon3: require('./home/Icons/Icon3.png'),
    UserIcon: require('./home/Icons/UserIcon.png'),
  },
  nft: {
    oscar: require('./nft/Oscar.png'),
    nft_bg: require('./nft/nft_bg.png'),
    nft_genesis_bg: require('./nft/nftgenesisbg.png'),
    nft_genesis_mobile_bg: require('./nft/nftgenesisMobilebg.png'),
    nft_card1: require('./nft/nft_card1.png'),
    nft_card2: require('./nft/nft_card2.png'),
    nft_card3: require('./nft/nft_card3.png'),
    nft_card4: require('./nft/nft_card4.png'),
    dynamicNftBg: require('./nft/dynamicNftBg.png'),
    rarityBg: require('./nft/rarityBg.png'),
    gold: require('./nft/Gold.png'),
    goldThumb: require('./nft/GoldThumb.png'),
    goldRect: require('./nft/goldRect.png'),
    platinum: require('./nft/Platinum.png'),
    platinuThumb: require('./nft/PlatinumThumb.png'),
    platinumRect: require('./nft/platinumRect.png'),
    bronze: require('./nft/Bronze.png'),
    bronzethumb: require('./nft/BronzeThumb.png'),
    bronzeRect: require('./nft/platinumRect.png'),
    nftOffer: require('./nft/NftOffer.png'),
    nftOfferBg: require('./nft/NftofferBg.png'),
  },
  whitelist: {
    nftpass: require('./whitelist/NftPass.png'),
    opportunitiesBg: require('./whitelist/opportunitiesBg.png'),
    whitelistHero: require('./whitelist/whitelist-hero-illustration.png'),
    impaktIconBg: require('./whitelist/impaktIconBg.png'),
  },
  group: {
    img: require('./group/img.png'),
    ellipse: require('./group/Ellipse.png'),
    cover: require('./group/cover.png'),
    group: require('./group/group.jpg'),
    upload: require('./group/Upload.png'),
    logo: require('./group/logo.png'),
    challengeBanner: require('./group/col.png'),
  },
  evolving: {
    evolving: require('./evolving.png'),
  },
  Journey: {
    Journey: require('./JourneyImg.png'),
    Journey1: require('./JourneyImg1.png'),
    Journey2: require('./JourneyImg2.png'),
  },
  kelvinImg: {
    kelvinImg: require('./kelvinImg.png'),
    photoMatt: require('./Photo_Matt.png'),
    photoUyen: require('./Photo_Uyen.png'),
    photoAaron: require('./Photo_Aaron.png'),
    photoAaron2: require('./Photo_Aaron2.png'),
    photoLevi: require('./Photo_Levi.png'),
  },
  Privacy: {
    PrivacyImg1: require('./PrivacyImg1.png'),
    PrivacyImg2: require('./PrivacyImg2.png'),
    PrivacyImg3: require('./PrivacyImg3.png'),
  },
  home: {
    HomeImage: require('./HomeImage.png'),
    hakim: require('./Hakim.png'),
    wiston: require('./wiston.png'),
  },
};

export default Images;
