/* eslint-disable no-unreachable */
/* eslint-disable global-require */

const Images = {
  dark: require('./dark.png'),
  light: require('./light.png'),
  star: require('./star.png'),
  background: require('./Background.png'),
  Common: {
    Logo: require('./logo.png'),
    HighResLogo: require('./high-res-impakt-logo.png'),
    LogoLight: require('./logo-light.png'),
    Twitter: require('./twitter.png'),
    TwitterLight: require('./twitter-light.png'),
    Youtube: require('./youtube-dark.png'),
    YoutubeLight: require('./youtube-light.png'),
    Discord: require('./discord.png'),
    DiscordLight: require('./discord-light.png'),
    Peter404: require('./peter404.png'),
    Window: require('./window.png'),
    Tiktok: require('./tiktok.png'),
    TiktokDark: require('./TiktokDark.png'),
    Facebook: require('./Facebook.png'),
    Instagram: require('./Instagram.png'),
    FacebookDark: require('./FacebookDark.png'),
    InstagramDark: require('./InstagramDark.png'),
    LinkedIn: require('./linkedin.png'),
    LinkedInDark: require('./linkedindark.png'),
    Walletad: require('./walletad.png'),
    Goldaword: require('./goldaword.png'),
  },
  backgrounds: {
    advisorsSectionBg: require('./bgadvvisors.png'),
    creedSectionBg: require('./bgcreed.png'),
    defaultBg: require('./bg.png'),
    gradientBg: require('./gradientbg.jpg'),
    gradientBgRotated: require('./gradientbgrotated.jpg'),
    light: require('./bg-light.png'),
    downloadAppBg: require('./downloadapp_bg.png'),
    teamofuseBg: require('./teamofusebg.png'),
    whitelistBg: require('./Whitelistbg.png'),
  },

  motionCapture: require('./motion-capture.webp'),
  burnAndEarn: require('./burn-to-earn-hero.webp'),
  computerVision: require('./computer-vision.png'),
  downloadlaptop: require('./download.png'),
  verification: require('./rich-icon.png'),
  wrong: require('./some-wrong.png'),

  impaktNFT: {
    Header: require('./nftbg.png'),
    light: require('./bg-light.png'),
    nftCard: require('./nft-flat.png'),
  },
  advisor: {
    kevin: require('./advisor/kevin.png'),
    tim: require('./advisor/tim.png'),
    kai: require('./advisor/kai.png'),
  },
  team: {
    // cap: require('./team/cap.png'),
    dahaka: require('./team/dahaka.png'),
    demideus: require('./team/demideus.png'),
    duke: require('./team/duke.png'),
    valtec: require('./team/valtec.png'),
    ratSpeare: require('./team/ratSpeare.png'),
    berila: require('./team/berila.png'),
    catRoutines: require('./team/catRoutines.png'),
    JSolo: require('./team/JSolo.png'),
    requiem: require('./team/requiem.png'),
    // dukeOfDeadfall: require('./team/duke-of-deadfall.png'),
  },
  contactUs: {
    discordPeter: require('./discordPeter.png'),
    hiPeter: require('./hiPeter.png'),
  },
  impaktIcons: {
    MattFox: require('./Matt-Fox.png'),
    KelvinGastelum: require('./Kelvin-Gastelum.png'),
    ThirdIcon: require('./thirdIcon.png'),
    Icon1: require('./Icons/Icon1.png'),
    Icon2: require('./Icons/Icon2.png'),
    Icon3: require('./Icons/Icon3.png'),
    UserIcon: require('./Icons/UserIcon.png'),
  },
  nft: {
    oscar: require('./nft/Oscar.png'),
    nft_bg: require('./nft/nft_bg.png'),
    nft_genesis_bg: require('./nft/nftgenesisbg.png'),
    nft_genesis_mobile_bg: require('./nft/nftgenesisMobilebg.png'),
    nft_card1: require('./nft/nft_card1.png'),
    nft_card2: require('./nft/nft_card2.png'),
    nft_card3: require('./nft/nft_card3.png'),
    nft_card4: require('./nft/nft_card4.png'),
  },
  evolving: {
    evolving: require('./evolving.png'),
  },
  Journey: {
    Journey: require('./JourneyImg.png'),
    Journey1: require('./JourneyImg1.png'),
    Journey2: require('./JourneyImg2.png'),
  },
  kelvinImg: {
    kelvinImg: require('./kelvinImg.png'),
    photoMatt: require('./Photo_Matt.png'),
    photoUyen: require('./Photo_Uyen.png'),
    photoAaron: require('./Photo_Aaron.png'),
    photoAaron2: require('./Photo_Aaron2.png'),
    photoLevi: require('./Photo_Levi.png'),
  },
  Privacy: {
    PrivacyImg1: require('./PrivacyImg1.png'),
    PrivacyImg2: require('./PrivacyImg2.png'),
    PrivacyImg3: require('./PrivacyImg3.png'),
  },
  home: {
    HomeImage: require('./HomeImage.png'),
    hakim: require('./Hakim.png'),
    wiston: require('./wiston.png'),
  },
};

export default Images;
