/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface CalendarEventDataDtoV1Response {
  id: number;
  title: string;
  description: string | null;
  creatorId: number;
  parentEventId: number | null;
  assocId: number | null;
  groupId?: number | null;
  createdAt: string;
  challengeId?: number | null;
}
