/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type CalendarDtoV1Type = typeof CalendarDtoV1Type[keyof typeof CalendarDtoV1Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CalendarDtoV1Type = {
  Personal: 'Personal',
  Group: 'Group',
} as const;
