/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface CalendarEventRescheduleRes {
  /** The event reschedule Id */
  id: number;
  /** The scheduled event Id */
  eventId: number;
  /** The timestamp of the event rescheduled */
  on: string;
  /** New start timestamp of the event */
  startDateTime: string;
  /** New end timestamp of the event */
  endDateTime: string;
  /** Rescheduled or not */
  rescheduled: boolean;
  /** Cancelled or not */
  cancelled: boolean;
  createdAt: string;
}
