/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type ChallengesControllerGetManyPublishableStatus =
  typeof ChallengesControllerGetManyPublishableStatus[keyof typeof ChallengesControllerGetManyPublishableStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChallengesControllerGetManyPublishableStatus = {
  Published: 'Published',
  Draft: 'Draft',
  Delisted: 'Delisted',
} as const;
