/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface ChallengeBestScoreStatsRes {
  /** 
  value is undefined in case user doesn't have any sessions for the specified challenge
   */
  userCount?: number | null;
  userTime?: number | null;
  userScore?: number | null;
}
