/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { CoinHistoryUserRecordV1 } from './coinHistoryUserRecordV1';

export interface CoinHistoryByUserIdV1Res {
  /** unsorted history records */
  data: CoinHistoryUserRecordV1[];
}
