/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityMemberResUser } from './communityMemberResUser';

export interface CommunityMemberRes {
  communityId: number;
  /** Shows if a user made this community as their primary community or not */
  primary: boolean;
  /** returns Id of the member joined a community */
  userId: number;
  /** returns a date a member joined the community */
  joinedAt?: string | null;
  /** returns the date member left the community */
  leftAt?: string | null;
  /** Associated member details */
  User: CommunityMemberResUser;
}
