/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Associated member details
 */
export type CommunityMemberResUser = { [key: string]: any };
