/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateGuestV1Dto {
  /** Guest name */
  screenName: string;
  /** Guest email */
  email?: string | null;
}
