/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type CreateLikeReqType = typeof CreateLikeReqType[keyof typeof CreateLikeReqType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateLikeReqType = {
  Challenge: 'Challenge',
  Routine: 'Routine',
  Post: 'Post',
  Comment: 'Comment',
  CalendarEvent: 'CalendarEvent',
} as const;
