/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateMailingListContactDto {
  /** Email to be added to the mailing list(s) */
  email: string;
  /** Mailing list Ids that are added on an email */
  mailingListIds?: string[] | null;
}
