/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateGameModeDefinitionDtoV1 {
  id: string;
  gameDefinitionId: string;
  parameters?: string | null;
}
