/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateCommentDto {
  /** This is the comment content */
  content: string;
  /** This is the Id of a comment that a reply is applied to, when provided, content is added as a reply */
  parentCommentId?: number | null;
}
