/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface DeleteManyTimelineBlocksReq {
  /** IDs of timeline blocks to delete */
  ids: number[];
}
