/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface EventDataDto {
  /** The title of the event */
  title: string;
  /** The description of the event */
  description: string;
  creatorId: number;
  assocId?: number;
  challengeId?: number;
  groupId?: number;
}
