/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type ExercisesControllerV1GetExercisesSupportedTypesItem =
  typeof ExercisesControllerV1GetExercisesSupportedTypesItem[keyof typeof ExercisesControllerV1GetExercisesSupportedTypesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExercisesControllerV1GetExercisesSupportedTypesItem = {
  Hold: 'Hold',
  Count: 'Count',
} as const;
