/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { ExercisesControllerV1GetExercisesStartPosition } from './exercisesControllerV1GetExercisesStartPosition';
import type { ExercisesControllerV1GetExercisesSupportedTypesItem } from './exercisesControllerV1GetExercisesSupportedTypesItem';

export type ExercisesControllerV1GetExercisesParams = {
  skip?: number | null;
  take?: number | null;
  name?: string | null;
  startPosition?: ExercisesControllerV1GetExercisesStartPosition;
  cvSupported?: boolean;
  supportedTypes?: ExercisesControllerV1GetExercisesSupportedTypesItem[];
};
