/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type FriendRequestsControllerFindAllDirection =
  typeof FriendRequestsControllerFindAllDirection[keyof typeof FriendRequestsControllerFindAllDirection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FriendRequestsControllerFindAllDirection = {
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
} as const;
