/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GameDefinitionResV1 } from './gameDefinitionResV1';

export interface GameDefinitionsResV1 {
  gameDefinitions: GameDefinitionResV1[];
  total: number;
  skip: number;
  take: number;
}
