/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface GetAppConfigClientValueV1 {
  /** JSON string. Needs to parse in app and type cast */
  value: string;
}
