/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { TagRes } from './tagRes';
import type { GetRoutineRes } from './getRoutineRes';
import type { GetRoutineToChallengeRes } from './getRoutineToChallengeRes';
import type { GetUserRes } from './getUserRes';

export interface GetChallengeRes {
  id: number;
  name: string;
  createdAt: string;
  updatedAt: string;
  creatorId: number;
  tags: TagRes[];
  validFrom: string;
  validUntil: string | null;
  /** only returned in Get requests by id */
  Routine: GetRoutineRes;
  likes: number;
  routineId: number;
  /**
   * Deprecated: Use base reward endpoint for calculating user specific values
   * @deprecated
   */
  baseReward: number;
  /**
   * always returned & ordered by validFrom
   * @deprecated
   */
  RoutinesToChallenges: GetRoutineToChallengeRes[];
  /** available only with Get methods */
  Creator?: GetUserRes;
}
