/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserRes } from './getUserRes';
import type { GetCommentResPost } from './getCommentResPost';

export interface GetCommentRes {
  id: number;
  creatorId: number;
  content: string;
  createdAt: string;
  /** Creator details */
  Creator: GetUserRes;
  /** Post details */
  Post: GetCommentResPost;
  /** Comment replies */
  ChildComments: GetCommentRes;
}
