/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetChallengeLeaderboardResV1RoutineType =
  typeof GetChallengeLeaderboardResV1RoutineType[keyof typeof GetChallengeLeaderboardResV1RoutineType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetChallengeLeaderboardResV1RoutineType = {
  HIIT: 'HIIT',
  Blitz: 'Blitz',
  Rhythm: 'Rhythm',
} as const;
