/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityMemberRes } from './communityMemberRes';

export interface GetCommunityMemberRes {
  id: number;
  name: string;
  /** returns if request is from /:communityId */
  description: string | null;
  /** returns if request is from /:communityId */
  ownerId: number | null;
  /** returns if request is from /:communityId */
  createdAt: string | null;
  /** returns available members of the community */
  members: CommunityMemberRes[];
}
