/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserRes } from './getUserRes';

export interface GetDeviceNotificationTokenRes {
  id: number;
  registrantId: number;
  deviceToken: string;
  platform: string;
  endpointArn: string;
  /** registrant details */
  registrant: GetUserRes;
  createdAt: string;
}
