/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetExerciseResV1SupportedTypesItem =
  typeof GetExerciseResV1SupportedTypesItem[keyof typeof GetExerciseResV1SupportedTypesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetExerciseResV1SupportedTypesItem = {
  Hold: 'Hold',
  Count: 'Count',
} as const;
