/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Available when Query filter by direction === SENT
 */
export type GetFriendRequestResTo = { [key: string]: any };
