/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface GetFavoriteRes {
  id: number;
  favoriteCollectionId: number;
  createdAt: string;
  type: string;
  objectId: number;
}
