/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetFriendRequestResStatus =
  typeof GetFriendRequestResStatus[keyof typeof GetFriendRequestResStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFriendRequestResStatus = {
  Pending: 'Pending',
  Accepted: 'Accepted',
  Declined: 'Declined',
} as const;
