/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetFriendRequestResFrom } from './getFriendRequestResFrom';
import type { GetFriendRequestResTo } from './getFriendRequestResTo';
import type { GetFriendRequestResStatus } from './getFriendRequestResStatus';

export interface GetFriendRequestRes {
  id: number;
  createdAt: string;
  fromUserId: number;
  /** Available when Query filter by direction === RECEIVED */
  from?: GetFriendRequestResFrom;
  /** Available when Query filter by direction === SENT */
  to?: GetFriendRequestResTo;
  toUserId: number;
  status: GetFriendRequestResStatus;
}
