/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetGroupRequestResPurpose =
  typeof GetGroupRequestResPurpose[keyof typeof GetGroupRequestResPurpose];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetGroupRequestResPurpose = {
  Pending: 'Pending',
  Accepted: 'Accepted',
  Declined: 'Declined',
  Cancelled: 'Cancelled',
} as const;
