/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetGroupMemberResWithUserRole } from './getGroupMemberResWithUserRole';
import type { GetUserRes } from './getUserRes';

export interface GetGroupMemberResWithUser {
  groupId: number;
  userId: number;
  joinedAt: string;
  leftAt: string | null;
  bannedAt: string | null;
  role: GetGroupMemberResWithUserRole;
  /** Associated member details */
  User: GetUserRes;
}
