/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface GetMailingListContactRes {
  /** Mailing list contact */
  email: string;
  /** List of mailing list Id(s), an email is added to */
  mailingListIds: string[] | null;
}
