/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserRes } from './getUserRes';
import type { GetCommentRes } from './getCommentRes';

export interface GetPostRes {
  id: number;
  creatorId: number;
  postCollectionId: number;
  content: string;
  createdAt: string;
  /** Creator details */
  Creator?: GetUserRes;
  /** Post comments */
  Comment: GetCommentRes[];
}
