/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

/**
 * user or guest
 */
export type GetPlayerScoreResV1Type =
  typeof GetPlayerScoreResV1Type[keyof typeof GetPlayerScoreResV1Type];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPlayerScoreResV1Type = {
  User: 'User',
  Guest: 'Guest',
} as const;
