/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetRoutineSessionResStatus =
  typeof GetRoutineSessionResStatus[keyof typeof GetRoutineSessionResStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoutineSessionResStatus = {
  InProgress: 'InProgress',
  Success: 'Success',
  Failed: 'Failed',
  Skipped: 'Skipped',
} as const;
