/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetRoutineToChallengeResChallengeType =
  typeof GetRoutineToChallengeResChallengeType[keyof typeof GetRoutineToChallengeResChallengeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRoutineToChallengeResChallengeType = {
  Daily: 'Daily',
  Weekly: 'Weekly',
} as const;
