/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoutineRes } from './getRoutineRes';
import type { GetRoutineToChallengeResChallengeType } from './getRoutineToChallengeResChallengeType';

export interface GetRoutineToChallengeRes {
  id: number;
  validFrom: string;
  validUntil: string | null;
  /** only returned in Get requests by id */
  Routine: GetRoutineRes;
  routineId: number;
  updatedAt: string;
  baseReward: number;
  challengeType: GetRoutineToChallengeResChallengeType;
  totalCount: number;
  xpMax: number;
  godlMax: number;
}
