/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetRoutineSessionResStatus } from './getRoutineSessionResStatus';
import type { GetRoutineSessionResStreak } from './getRoutineSessionResStreak';

export interface GetRoutineSessionRes {
  id: number;
  routineId?: number;
  createdAt: string;
  updatedAt: string;
  completedAt?: string | null;
  status: GetRoutineSessionResStatus;
  streak: GetRoutineSessionResStreak;
  /** @deprecated */
  reward: number | null;
  godl: number;
  userScore: number;
  xp: number;
  coin: number;
}
