/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetServerEnvResV1Env } from './getServerEnvResV1Env';

export interface GetServerEnvResV1 {
  env: GetServerEnvResV1Env;
}
