/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetServerEnvResV1Env = typeof GetServerEnvResV1Env[keyof typeof GetServerEnvResV1Env];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetServerEnvResV1Env = {
  dev: 'dev',
  test: 'test',
  stage: 'stage',
  prod: 'prod',
  build_only: 'build_only',
} as const;
