/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetTimelineBlockSessionResType =
  typeof GetTimelineBlockSessionResType[keyof typeof GetTimelineBlockSessionResType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTimelineBlockSessionResType = {
  Rest: 'Rest',
  HoldPose: 'HoldPose',
  HIIT: 'HIIT',
  Blitz: 'Blitz',
  Rhythm: 'Rhythm',
} as const;
