/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTimelineBlockAttributeResType } from './getTimelineBlockAttributeResType';

export interface GetTimelineBlockAttributeRes {
  id: number;
  type: GetTimelineBlockAttributeResType;
  value: number;
  timelineBlockId: number;
  updatedAt: string;
  createdAt: string;
}
