/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetTimelineBlockResGroup =
  typeof GetTimelineBlockResGroup[keyof typeof GetTimelineBlockResGroup];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTimelineBlockResGroup = {
  WarmUp: 'WarmUp',
  Main: 'Main',
  CoolDown: 'CoolDown',
} as const;
