/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GetUserResRolesItem = typeof GetUserResRolesItem[keyof typeof GetUserResRolesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserResRolesItem = {
  SuperAdmin: 'SuperAdmin',
  Admin: 'Admin',
  Creator: 'Creator',
  Tester: 'Tester',
  Ambassador: 'Ambassador',
  Whitelist: 'Whitelist',
  Partner: 'Partner',
} as const;
