/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserResRolesItem } from './getUserResRolesItem';
import type { GetCommunityRes } from './getCommunityRes';

export interface GetUserRes {
  id: number;
  /** List of user given roles */
  Roles: GetUserResRolesItem[] | null;
  email: string | null;
  username: string;
  firstName: string | null;
  lastName: string | null;
  discordHandle: string | null;
  cryptoWallet: string | null;
  createdAt: string;
  updatedAt: string;
  primaryCommunityId: number | null;
  Communities: GetCommunityRes[] | null;
  DiscourseRedirectUrl: string | null;
  emailVerified: boolean;
  calendarId: number;
  /** List of mailing list Id(s), a user is subscribed to */
  mailingListIds: string[];
}
