/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface GetUploadUrlRes {
  /** Pre-signed Upload Object URL */
  uploadLink: string;
  /** Generated AWS Console S3 Object URL */
  downloadLink: string;
}
