/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface GodlBaseRewardRes {
  /** Challenge id that should be rewarded */
  challengeId: number;
  /** Base reward */
  baseReward: number;
}
