/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GodlChallengeControllerGetChallengesBaseRewardParams = {
  skip?: number | null;
  take?: number | null;
  challengeId?: number[];
};
