/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GodlHistoryUserRecordV1Purpose =
  typeof GodlHistoryUserRecordV1Purpose[keyof typeof GodlHistoryUserRecordV1Purpose];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GodlHistoryUserRecordV1Purpose = {
  Transfer: 'Transfer',
  ChallengeReward: 'ChallengeReward',
  ChallengeCreatorReward: 'ChallengeCreatorReward',
  TimelineBlock: 'TimelineBlock',
  Referral: 'Referral',
  SignUp: 'SignUp',
  AdminReward: 'AdminReward',
  DailyReward: 'DailyReward',
} as const;
