/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GodlHistoryUserRecordV1 } from './godlHistoryUserRecordV1';

export interface GoldHistoryByUserIdV1Res {
  /** unsorted history records */
  data: GodlHistoryUserRecordV1[];
}
