/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupsRequestControllerV1GetGroupRequestsStatus } from './groupsRequestControllerV1GetGroupRequestsStatus';

export type GroupsRequestControllerV1GetGroupRequestsParams = {
  skip?: number | null;
  take?: number | null;
  status?: GroupsRequestControllerV1GetGroupRequestsStatus;
};
