/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type GroupsMemberControllerV1AssignGroupRoleRole =
  typeof GroupsMemberControllerV1AssignGroupRoleRole[keyof typeof GroupsMemberControllerV1AssignGroupRoleRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupsMemberControllerV1AssignGroupRoleRole = {
  Creator: 'Creator',
  Owner: 'Owner',
  Admin: 'Admin',
  Moderator: 'Moderator',
  Member: 'Member',
  None: 'None',
} as const;
