/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The player type
 */
export type LeaderboardCreateDtoV1Player =
  typeof LeaderboardCreateDtoV1Player[keyof typeof LeaderboardCreateDtoV1Player];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeaderboardCreateDtoV1Player = {
  User: 'User',
  Guest: 'Guest',
} as const;
