/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { LeaderboardCreateDtoV1Player } from './leaderboardCreateDtoV1Player';

export interface LeaderboardCreateDtoV1 {
  /** The player type */
  player: LeaderboardCreateDtoV1Player;
  /** The player ID */
  playerId: number;
  /** The event ID */
  eventId?: number | null;
  /** The score */
  score: number;
  /** The game ID */
  gameDefinitionId?: string | null;
}
