/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { LeaderboardControllerV1GetLeaderboardPlayer } from './leaderboardControllerV1GetLeaderboardPlayer';

export type LeaderboardControllerV1GetLeaderboardParams = {
  take?: number | null;
  skip?: number | null;
  player?: LeaderboardControllerV1GetLeaderboardPlayer;
  playerId?: number | null;
  eventId?: number | null;
  fromDate?: string | null;
  gameModeDefinitionId?: string | null;
};
