/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type MessageControllerV1GetMessagesParams = {
  take?: number | null;
  skip?: number | null;
  cursorId?: number | null;
};
