/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageV1Dto } from './messageV1Dto';

export interface MessagesV1Dto {
  count: number;
  take: number;
  skip: number;
  messages: MessageV1Dto[];
}
