/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchRoutineReqType } from './patchRoutineReqType';

export interface PatchRoutineReq {
  name?: string | null;
  type?: PatchRoutineReqType;
  /** Tag by value to add */
  addTags?: string[] | null;
  /** Tag by value to remove */
  removeTags?: string[] | null;
}
