/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Publishable Status of a challenge - Published: Active, Delisted: expired(automatic or manual), Draft: Not available
 */
export type PatchChallengeReqPublishableStatus =
  typeof PatchChallengeReqPublishableStatus[keyof typeof PatchChallengeReqPublishableStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchChallengeReqPublishableStatus = {
  Published: 'Published',
  Draft: 'Draft',
  Delisted: 'Delisted',
} as const;
