/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchExerciseReqV1SupportedTypesItem } from './patchExerciseReqV1SupportedTypesItem';

export interface PatchExerciseReqV1 {
  name?: string | null;
  cvSupported?: boolean | null;
  startPosition?: string | null;
  /** Replaces exisiting list with the one received */
  supportedTypes: PatchExerciseReqV1SupportedTypesItem[];
  /** Average time per rep in ms; ex: 1500 */
  averageTime: number;
  point: number;
}
