/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { EventRescheduleReq } from './eventRescheduleReq';

export interface PatchCalendarEventReq {
  /** The title of the event */
  title: string;
  /** The description of the event */
  description: string;
  assocId?: number;
  challengeId?: number;
  reschedule?: EventRescheduleReq;
}
