/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchTimelineBlockReq } from './patchTimelineBlockReq';

export interface PatchManyTimelineBlockReq {
  /** Patch an array of timeline blocks, including attributes */
  data: PatchTimelineBlockReq[];
}
