/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type PatchExerciseReqV1SupportedTypesItem =
  typeof PatchExerciseReqV1SupportedTypesItem[keyof typeof PatchExerciseReqV1SupportedTypesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchExerciseReqV1SupportedTypesItem = {
  Hold: 'Hold',
  Count: 'Count',
} as const;
