/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Accept or Decline Status Filter
 */
export type PatchGroupRequestReqStatus =
  typeof PatchGroupRequestReqStatus[keyof typeof PatchGroupRequestReqStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchGroupRequestReqStatus = {
  Accepted: 'Accepted',
  Declined: 'Declined',
} as const;
