/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type PatchRoutineReqType = typeof PatchRoutineReqType[keyof typeof PatchRoutineReqType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchRoutineReqType = {
  HIIT: 'HIIT',
  Blitz: 'Blitz',
  Rhythm: 'Rhythm',
} as const;
