/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchChallengeReqPublishableStatus } from './patchChallengeReqPublishableStatus';

export interface PatchChallengeReq {
  name?: string | null;
  description?: string | null;
  /** Tag by value to add */
  addTags?: string[] | null;
  /** Tag by value to remove */
  removeTags?: string[] | null;
  /** Publishable Status of a challenge - Published: Active, Delisted: expired(automatic or manual), Draft: Not available */
  PublishableStatus?: PatchChallengeReqPublishableStatus;
}
