/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface PatchUserReq {
  email?: string | null;
  /** Required if email, cryptoWallet isn't null */
  password?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  newPassword?: string | null;
  /** Required if newPassword is not null */
  oldPassword?: string | null;
  username?: string | null;
  discordHandle?: string | null;
  cryptoWallet?: string | null;
  /** Pass multiple ids to be joined by the user */
  communities?: number[] | null;
  /** Mark a community as primary by id, ID must exist in communities */
  primaryCommunityId?: number | null;
}
