/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type PatchRoutineSessionReqStatus =
  typeof PatchRoutineSessionReqStatus[keyof typeof PatchRoutineSessionReqStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchRoutineSessionReqStatus = {
  InProgress: 'InProgress',
  Success: 'Success',
  Failed: 'Failed',
  Skipped: 'Skipped',
} as const;
