/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { EventDataDto } from './eventDataDto';
import type { EventScheduleDto } from './eventScheduleDto';

export interface PostCalendarEventReq {
  /** Event data */
  data: EventDataDto;
  /** Event data */
  schedule: EventScheduleDto;
}
