/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface PostTimelineBlockSessionReq {
  /** ID of the timelineBlock */
  timelineBlockId: number;
  /** ID of the active routineSession */
  routineSessionId: number;
}
