/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { PostRoutineReqType } from './postRoutineReqType';
import type { PostTimelineBlockReq } from './postTimelineBlockReq';

export interface PostRoutineReq {
  name: string;
  type: PostRoutineReqType;
  /** Tag by value to add */
  addTags?: string[] | null;
  TimelineBlocks?: PostTimelineBlockReq[] | null;
}
