/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { PostTagReqAvailableForItem } from './postTagReqAvailableForItem';

export interface PostTagReq {
  value: string;
  availableFor: PostTagReqAvailableForItem[];
}
