/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type PostControllerV1GetManyParams = {
  skip?: number | null;
  take?: number | null;
  creatorId?: number | null;
  notCreatorId?: number | null;
};
