/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface PostUserRewardReq {
  /** Username of a user to be rewarded */
  username: string;
  /** Godl amount to be rewarded */
  amount: number;
}
