/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type PostTagReqAvailableForItem =
  typeof PostTagReqAvailableForItem[keyof typeof PostTagReqAvailableForItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostTagReqAvailableForItem = {
  Challenges: 'Challenges',
  Routines: 'Routines',
} as const;
