/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface PostUserReq {
  username?: string | null;
  password: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  discordHandle?: string | null;
  cryptoWallet?: string | null;
  /** Mark a community as primary by id, ID must exist in communities */
  primaryCommunityId?: number | null;
  referrerId?: number | null;
  /** Pass multiple ids to be joined by the user */
  communities?: number[] | null;
  /** minigameBonus flag when true, we reward 5000 KOIN otherwise we reward nothing */
  minigameBonus?: boolean | null;
  /** Mailing list Ids user wants to subscribe to */
  mailingListIds?: string[] | null;
}
