/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type PostExerciseReqV1SupportedTypesItem =
  typeof PostExerciseReqV1SupportedTypesItem[keyof typeof PostExerciseReqV1SupportedTypesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostExerciseReqV1SupportedTypesItem = {
  Hold: 'Hold',
  Count: 'Count',
} as const;
