/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface ReferralTransactionRes {
  /** User ID of the account */
  id: number;
  /** account */
  amount: number;
}
