/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterdeviceTokenDtoPlatform } from './registerdeviceTokenDtoPlatform';

export interface RegisterdeviceTokenDto {
  /** This is the the unique identifier created by the notification service for an app on a device. */
  deviceToken: string;
  platform: RegisterdeviceTokenDtoPlatform;
}
