/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type RegisterdeviceTokenDtoPlatform =
  typeof RegisterdeviceTokenDtoPlatform[keyof typeof RegisterdeviceTokenDtoPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterdeviceTokenDtoPlatform = {
  ANDROID: 'ANDROID',
  IOS: 'IOS',
  MACOS: 'MACOS',
  WINDOWS: 'WINDOWS',
} as const;
