/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type RewardHistoryControllerV1GetRewardHistoryReferenceTypeItem =
  typeof RewardHistoryControllerV1GetRewardHistoryReferenceTypeItem[keyof typeof RewardHistoryControllerV1GetRewardHistoryReferenceTypeItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RewardHistoryControllerV1GetRewardHistoryReferenceTypeItem = {
  Daily: 'Daily',
  Referral: 'Referral',
  SignUp: 'SignUp',
  Admin: 'Admin',
  TimelineBlockSession: 'TimelineBlockSession',
  GroupLevelUp: 'GroupLevelUp',
  GroupLevelDown: 'GroupLevelDown',
} as const;
