/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { RoutinesControllerGetRoutinesType } from './routinesControllerGetRoutinesType';

export type RoutinesControllerGetRoutinesParams = {
  skip?: number | null;
  take?: number | null;
  type?: RoutinesControllerGetRoutinesType;
  name?: string | null;
  creatorId?: number | null;
  Creator?: boolean | null;
  TimelineBlocks?: boolean | null;
  tag?: string | null;
  notCreatorId?: number | null;
};
