/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { TagResAvailableForItem } from './tagResAvailableForItem';

export interface TagRes {
  id: number;
  createdAt: string;
  value: string;
  availableFor: TagResAvailableForItem[];
}
