/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineBlocksControllerGetTimeBlocksType } from './timelineBlocksControllerGetTimeBlocksType';

export type TimelineBlocksControllerGetTimeBlocksParams = {
  skip?: number | null;
  take?: number | null;
  Exercise?: boolean;
  TimelineBlockAttributes?: boolean;
  type?: TimelineBlocksControllerGetTimeBlocksType;
  routineId: number;
};
