/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadControllerUploadFileFileType } from './uploadControllerUploadFileFileType';

export type UploadControllerUploadFileParams = { fileType: UploadControllerUploadFileFileType };
