/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadControllerGetUploadUrlUploadType } from './uploadControllerGetUploadUrlUploadType';

export type UploadControllerGetUploadUrlParams = {
  uploadType: UploadControllerGetUploadUrlUploadType;
  filename: string;
  routineSessionId?: number | null;
  uuid?: string | null;
};
