/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type UploadControllerUploadFileReference =
  typeof UploadControllerUploadFileReference[keyof typeof UploadControllerUploadFileReference];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadControllerUploadFileReference = {
  UserThumbnail: 'UserThumbnail',
  PracticeRoom: 'PracticeRoom',
  RoutineSession: 'RoutineSession',
  GroupCoverImage: 'GroupCoverImage',
  GroupThumbnail: 'GroupThumbnail',
  GroupProfile: 'GroupProfile',
} as const;
