/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type UploadControllerUploadCvRef =
  typeof UploadControllerUploadCvRef[keyof typeof UploadControllerUploadCvRef];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadControllerUploadCvRef = {
  PracticeRoom: 'PracticeRoom',
  RoutineSession: 'RoutineSession',
} as const;
