/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { UserControllerGetUsersRolesItem } from './userControllerGetUsersRolesItem';

export type UserControllerGetUsersParams = {
  skip?: number | null;
  take?: number | null;
  Communities?: boolean | null;
  username?: string | null;
  discordHandle?: string | null;
  Roles?: UserControllerGetUsersRolesItem[] | null;
};
