/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface UserStreak {
  /** 
    Streak value in Days
   */
  value: number;
  /** 
    Returned with current streak, if last streak is yesterday or none will be false
     */
  streakedToday: boolean | null;
  /**
   * 
    Returned with longest streak
  
   * @deprecated
   */
  completedAt: string | null;
}
