/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export interface UserStatsGetActiveMembersRes {
  /** Number of active members for given period */
  count: number;
}
