/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */

export type UtilsControllerV1CheckFreeFieldsParams = {
  username?: string | null;
  email?: string | null;
};
