/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { XpHistoryUserRecordV1 } from './xpHistoryUserRecordV1';

export interface XpHistoryByUserIdV1Res {
  /** number of xp rewards history found */
  count: number;
  /** total xp rewards found */
  value: number;
  /** xp rewards history */
  data: XpHistoryUserRecordV1[];
}
