/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import type { XpHistoryUserRecordV1Purpose } from './xpHistoryUserRecordV1Purpose';

export interface XpHistoryUserRecordV1 {
  purpose: XpHistoryUserRecordV1Purpose;
  timestamp: string;
  value: number;
}
