/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import { rest } from 'msw';
import { faker } from '@faker-js/faker';

export const getAuthControllerLoginMock = () => ({
  id: faker.datatype.number({ min: undefined, max: undefined }),
  Roles: faker.helpers.arrayElement([
    'SuperAdmin',
    'Admin',
    'Creator',
    'Tester',
    'Ambassador',
    'Whitelist',
    'Partner',
  ]),
  email: faker.helpers.arrayElement([faker.random.word(), null]),
  username: faker.random.word(),
  firstName: faker.helpers.arrayElement([faker.random.word(), null]),
  lastName: faker.helpers.arrayElement([faker.random.word(), null]),
  discordHandle: faker.helpers.arrayElement([faker.random.word(), null]),
  cryptoWallet: faker.helpers.arrayElement([faker.random.word(), null]),
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  primaryCommunityId: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    null,
  ]),
  Communities: Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.datatype.number({ min: undefined, max: undefined }),
    name: faker.random.word(),
    description: faker.helpers.arrayElement([faker.random.word(), null]),
    ownerId: faker.helpers.arrayElement([
      faker.datatype.number({ min: undefined, max: undefined }),
      null,
    ]),
    createdAt: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      null,
    ]),
    updatedAt: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      null,
    ]),
    memberCount: faker.datatype.number({ min: undefined, max: undefined }),
  })),
  DiscourseRedirectUrl: faker.helpers.arrayElement([faker.random.word(), null]),
  emailVerified: faker.datatype.boolean(),
});

export const getAuthControllerSignAccessTokenMock = () => ({
  id: faker.datatype.number({ min: undefined, max: undefined }),
  Roles: faker.helpers.arrayElement([
    'SuperAdmin',
    'Admin',
    'Creator',
    'Tester',
    'Ambassador',
    'Whitelist',
    'Partner',
  ]),
  email: faker.helpers.arrayElement([faker.random.word(), null]),
  username: faker.random.word(),
  firstName: faker.helpers.arrayElement([faker.random.word(), null]),
  lastName: faker.helpers.arrayElement([faker.random.word(), null]),
  discordHandle: faker.helpers.arrayElement([faker.random.word(), null]),
  cryptoWallet: faker.helpers.arrayElement([faker.random.word(), null]),
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  primaryCommunityId: faker.helpers.arrayElement([
    faker.datatype.number({ min: undefined, max: undefined }),
    null,
  ]),
  Communities: Array.from(
    { length: faker.datatype.number({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.datatype.number({ min: undefined, max: undefined }),
    name: faker.random.word(),
    description: faker.helpers.arrayElement([faker.random.word(), null]),
    ownerId: faker.helpers.arrayElement([
      faker.datatype.number({ min: undefined, max: undefined }),
      null,
    ]),
    createdAt: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      null,
    ]),
    updatedAt: faker.helpers.arrayElement([
      `${faker.date.past().toISOString().split('.')[0]}Z`,
      null,
    ]),
    memberCount: faker.datatype.number({ min: undefined, max: undefined }),
  })),
  DiscourseRedirectUrl: faker.helpers.arrayElement([faker.random.word(), null]),
  emailVerified: faker.datatype.boolean(),
});

export const getAuthMSW = () => [
  rest.post('*/api/v1/iam/auth/signin', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getAuthControllerLoginMock()),
    );
  }),
  rest.post('*/api/v1/iam/auth/signout', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.post('*/api/v1/iam/auth/refresh', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getAuthControllerSignAccessTokenMock()),
    );
  }),
  rest.post('*/api/v1/iam/auth/verification/request', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.get('*/api/v1/iam/auth/verification/:header.:payload.:signature', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.post('*/api/v1/iam/auth/passwordReset/:header.:payload.:signature', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.post('*/api/v1/iam/auth/passwordReset', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.get('*/api/v1/iam/auth/discord/login', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.get('*/api/v1/iam/auth/discord/redirect', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.get('*/api/v1/iam/auth/twitter', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.get('*/api/v1/iam/auth/twitter/redirect', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
];
