/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey,
} from '@tanstack/react-query';
import type {
  XpHistoryByUserIdV1Res,
  XpHistoryControllerV1GetHistoryByUserIdParams,
} from '../types';
import { customInstance } from '../../custom-instance';
import type { ErrorType } from '../../custom-instance';

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

export const xpHistoryControllerV1GetHistoryByUserId = (
  userId: number,
  params?: XpHistoryControllerV1GetHistoryByUserIdParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<XpHistoryByUserIdV1Res>(
    { url: `/api/v1/xp/history/${userId}`, method: 'get', params, signal },
    options,
  );
};

export const getXpHistoryControllerV1GetHistoryByUserIdQueryKey = (
  userId: number,
  params?: XpHistoryControllerV1GetHistoryByUserIdParams,
) => [`/api/v1/xp/history/${userId}`, ...(params ? [params] : [])];

export type XpHistoryControllerV1GetHistoryByUserIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof xpHistoryControllerV1GetHistoryByUserId>>
>;
export type XpHistoryControllerV1GetHistoryByUserIdQueryError = ErrorType<unknown>;

export const useXpHistoryControllerV1GetHistoryByUserId = <
  TData = Awaited<ReturnType<typeof xpHistoryControllerV1GetHistoryByUserId>>,
  TError = ErrorType<unknown>,
>(
  userId: number,
  params?: XpHistoryControllerV1GetHistoryByUserIdParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof xpHistoryControllerV1GetHistoryByUserId>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getXpHistoryControllerV1GetHistoryByUserIdQueryKey(userId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof xpHistoryControllerV1GetHistoryByUserId>>
  > = ({ signal }) =>
    xpHistoryControllerV1GetHistoryByUserId(userId, params, requestOptions, signal);

  const query = useQuery<
    Awaited<ReturnType<typeof xpHistoryControllerV1GetHistoryByUserId>>,
    TError,
    TData
  >(queryKey, queryFn, { enabled: !!userId, ...queryOptions }) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryKey;

  return query;
};
