export { default as HeroVideoSection } from 'components/ui/Landing/HeroVideoSection';
export { default as MyBody } from 'components/ui/Landing/MyBody/MyBody';
export { default as Athletes } from 'components/ui/Landing/Athletes';
export { default as ImpaktTeam } from 'components/ui/Landing/ImpaktTeam';
export { default as HumanNeed } from 'components/ui/Landing/HumanNeed';
export { default as Privacy } from 'components/ui/Landing/Privacy';
export { default as Evolving } from 'components/ui/Landing/Evolving';
export { default as FitnessJourney } from 'components/ui/Landing/FitnessJourney';
export { default as BecomePart } from 'components/ui/Landing/BecomePart';
