/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import { rest } from 'msw';
import { faker } from '@faker-js/faker';

export const getUploadControllerGetUploadUrlMock = () => ({
  uploadLink: faker.random.word(),
  downloadLink: faker.random.word(),
});

export const getUploadControllerUploadFileMock = () => faker.datatype.boolean();

export const getUploadsMSW = () => [
  rest.get('*/api/v1/uploads/upload-url', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getUploadControllerGetUploadUrlMock()),
    );
  }),
  rest.post('*/api/v1/uploads/upload-file', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getUploadControllerUploadFileMock()),
    );
  }),
];
