/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Impakt API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  QueryFunction,
  UseQueryResult,
  QueryKey,
} from '@tanstack/react-query';
import type { CalendarDtoV1, HttpExceptionSchema } from '../types';
import { customInstance } from '../../custom-instance';
import type { ErrorType } from '../../custom-instance';

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

export const calendarControllerGetCalendarListView = (
  calendarId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CalendarDtoV1>(
    { url: `/api/v1/calendar/calendar/${calendarId}/list`, method: 'get', signal },
    options,
  );
};

export const getCalendarControllerGetCalendarListViewQueryKey = (calendarId: number) => [
  `/api/v1/calendar/calendar/${calendarId}/list`,
];

export type CalendarControllerGetCalendarListViewQueryResult = NonNullable<
  Awaited<ReturnType<typeof calendarControllerGetCalendarListView>>
>;
export type CalendarControllerGetCalendarListViewQueryError = ErrorType<HttpExceptionSchema>;

export const useCalendarControllerGetCalendarListView = <
  TData = Awaited<ReturnType<typeof calendarControllerGetCalendarListView>>,
  TError = ErrorType<HttpExceptionSchema>,
>(
  calendarId: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof calendarControllerGetCalendarListView>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCalendarControllerGetCalendarListViewQueryKey(calendarId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof calendarControllerGetCalendarListView>>
  > = ({ signal }) => calendarControllerGetCalendarListView(calendarId, requestOptions, signal);

  const query = useQuery<
    Awaited<ReturnType<typeof calendarControllerGetCalendarListView>>,
    TError,
    TData
  >(queryKey, queryFn, { enabled: !!calendarId, ...queryOptions }) as UseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
};
